# application.yml
server:
  port: ${PORT:8080}
  servlet:
    context-path: "/upload-download/v1"

spring:
  application:
    name: upload-download
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 300MB

backend-configs:
  aws:
    s3:
      bucket: ${AWS_S3_BUCKET}
      path-name: ${AWS_S3_PATH_NAME}
    credentials:
      key.id: ${AWS_ACCESS_KEY_ID}
      secret.key: ${AWS_ACCESS_SECRET}
    region: ${AWS_REGION}
    msk:
      brokers: ${AWS_MSK_BROKERS}
      topic-name: ${AWS_MSK_TOPIC_NAME}
  client:
    process.url: ${CLIENT_PROCESS_URL}
    user.url: ${CLIENT_USER_URL}
  upload:
    video-max-file-size-mb: ${MAX_FILE_SIZE_IN_MB_UPLOAD}
    video-max-duration-seconds: ${MAX_DURATION_IN_SECONDS_VIDEO}

# swagger-ui and api-docs custom path
springdoc:
  swagger-ui:
    path: "/swagger-ui"
  api-docs:
    path: "/api-docs"